(() => {
"use strict";
const C=window.STREAMHUB_CONFIG||{};
const db=window.supabase.createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const ADMIN_UID="56a4036e-b37d-4928-abf2-8f49d709f5b7";
let streamers=[],activeGame=null,currentUser=null,currentProfile=null;
const games=[
 {name:"Fortnite",art:"https://ogre.natalie.mu/media/news/music/2020/0731/Fortnite_keyart.jpg?imdensity=1&imwidth=1200"},
 {name:"Minecraft",art:"https://www.minecraft.net/content/dam/minecraftnet/games/minecraft/key-art/PDP-Hero_OV-Deluxe_16x9.jpg"},
 {name:"Call of Duty: Warzone",art:"https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1962663/header.jpg"},
 {name:"Apex Legends",art:"https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1172470/header.jpg"},
 {name:"Grand Theft Auto V",art:"https://media-rockstargames-com.akamaized.net/rockstargames-newsite/img/global/games/fob/1280/V.jpg"}
];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function toast(m,bad=false){const t=document.getElementById("toast");t.textContent=m;t.className="toast show "+(bad?"":"good");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.className="toast",5000)}
function openModal(body){document.getElementById("modalRoot").innerHTML=`<div class="modal-back" id="modalBack"><div class="modal"><button class="close-btn" id="closeModal">×</button>${body}</div></div>`;document.getElementById("closeModal").onclick=closeModal;document.getElementById("modalBack").onclick=e=>{if(e.target.id==="modalBack")closeModal()}}
function closeModal(){document.getElementById("modalRoot").innerHTML=""}
function card(s){const img=s.thumbnail_url||s.avatar_url||"https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=900&q=80";return `<article class="card"><div class="preview"><img src="${esc(img)}" alt="${esc(s.name)} thumbnail" loading="lazy"><span class="badge ${s.is_live?"":"offline"}">${s.is_live?"● LIVE":"OFFLINE"}</span>${s.is_live?`<span class="viewers">👁 ${Number(s.viewers||0).toLocaleString("et-EE")}</span>`:""}</div><div class="cardbody"><div class="cardtitle">${esc(s.name)}</div><div class="meta">${esc(s.game||"Streaming")} · ${esc(s.platform)}</div><a class="cardlink" href="${esc(s.channel_url)}" target="_blank" rel="noopener">${s.is_live?"VAATA LIVE'I →":"AVA KANAL →"}</a></div></article>`}
async function loadStreamers(){const {data,error}=await db.from("streamers").select("*").order("is_live",{ascending:false}).order("viewers",{ascending:false}).order("name");if(error){toast("Striimerite laadimine ebaõnnestus: "+error.message,true);return}streamers=data||[];render()}
function render(){const q=(document.getElementById("search")?.value||"").toLowerCase();let rows=streamers.filter(s=>!activeGame||String(s.game||"").toLowerCase()===activeGame.toLowerCase());rows=rows.filter(s=>`${s.name} ${s.game||""}`.toLowerCase().includes(q));document.getElementById("liveGrid").innerHTML=rows.filter(s=>s.is_live).map(card).join("")||`<div class="empty">Hetkel pole valitud vaates ühtegi LIVE striimerit.</div>`;document.getElementById("streamerGrid").innerHTML=rows.map(card).join("")||`<div class="empty">Ühtegi striimerit ei leitud.</div>`;renderGames(rows)}
function renderGames(rows=streamers){document.getElementById("gameStrip").innerHTML=games.map(g=>`<button type="button" aria-label="${esc(g.name)}" class="game-tile ${activeGame===g.name?"active":""}" data-game="${esc(g.name)}"><span class="game-art" style="background-image:url("${g.art}")"></span><span class="game-name">${esc(g.name)}</span><span class="game-count">${streamers.filter(s=>String(s.game||"").trim().toLowerCase()===g.name.toLowerCase() && s.is_live).length} LIVE</span></button>`).join("");document.querySelectorAll(".game-tile").forEach(b=>b.onclick=()=>{activeGame=b.dataset.game;document.getElementById("games").scrollIntoView({behavior:"smooth",block:"start"});render()});const gr=document.getElementById("gameResults");if(!activeGame){gr.classList.add("hidden");return}const found=streamers.filter(s=>String(s.game||"").toLowerCase()===activeGame.toLowerCase());gr.classList.remove("hidden");gr.innerHTML=`<div class="game-results-title">${esc(activeGame)} — ${found.length} striimerit</div><div class="game-results-grid">${found.map(card).join("")||`<div class="empty">Selle mängu all pole veel striimereid.</div>`}</div>`}
function platformFilters(){const ps=["Kõik","Twitch","YouTube","Kick","TikTok"];document.getElementById("platformFilters").innerHTML=ps.map((p,i)=>`<button class="filter ${i===0?"active":""}" data-platform="${p}">${p}</button>`).join("");document.querySelectorAll("[data-platform]").forEach(b=>b.onclick=()=>{const p=b.dataset.platform;document.querySelectorAll("[data-platform]").forEach(x=>x.classList.remove("active"));b.classList.add("active");const q=(document.getElementById("search").value||"").toLowerCase();const rows=streamers.filter(s=>(p==="Kõik"||s.platform===p)&&(!activeGame||String(s.game||"").toLowerCase()===activeGame.toLowerCase())&&`${s.name} ${s.game||""}`.toLowerCase().includes(q));document.getElementById("liveGrid").innerHTML=rows.filter(s=>s.is_live).map(card).join("")||`<div class="empty">Hetkel pole LIVE striimereid.</div>`;document.getElementById("streamerGrid").innerHTML=rows.map(card).join("")||`<div class="empty">Ühtegi striimerit ei leitud.</div>`})}
function accountModal(tab="login"){openModal(`<div class="eyebrow">STREAMHUB KASUTAJA</div><h2>Kasutaja</h2><div class="account-tabs"><button class="btn ${tab==="login"?"primary":""}" id="tabLogin">Logi sisse</button><button class="btn ${tab==="signup"?"" : ""}" id="tabSignup">Loo konto</button><button class="btn" id="tabJoin">Liitu striimerina</button></div><div id="accountBody"></div>`);document.getElementById("tabLogin").onclick=()=>accountModal("login");document.getElementById("tabSignup").onclick=()=>accountModal("signup");document.getElementById("tabJoin").onclick=()=>joinModal();if(tab==="signup")signupForm();else loginForm()}
function loginForm(){document.getElementById("accountBody").innerHTML=`<form id="loginForm" class="formgrid"><div class="field"><label>E-POST</label><input name="email" type="email" required></div><div class="field"><label>PAROOL</label><input name="password" type="password" required></div><button class="primary full">LOGI SISSE</button><div id="accountError" class="notice error hidden"></div></form>`;document.getElementById("loginForm").onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e));const {data,error}=await db.auth.signInWithPassword({email:d.email.trim(),password:d.password});if(error){showAccountError(error.message);return}currentUser=data.user;await loadProfile();closeModal();toast("Sisse logitud.");if(currentProfile?.role==="admin"||currentUser.id===ADMIN_UID)adminModal();else userModal()}}
function signupForm(){document.getElementById("accountBody").innerHTML=`<form id="signupForm" class="formgrid"><div class="field"><label>KASUTAJANIMI</label><input name="username" required minlength="2" maxlength="40"></div><div class="field"><label>E-POST</label><input name="email" type="email" required></div><div class="field"><label>PAROOL</label><input name="password" type="password" minlength="6" required></div><div class="field"><label>PAROOL UUESTI</label><input name="password2" type="password" minlength="6" required></div><button class="primary full">LOO KONTO</button><div id="accountError" class="notice error hidden"></div></form>`;document.getElementById("signupForm").onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e));if(d.password!==d.password2){showAccountError("Paroolid ei kattu.");return}const {data,error}=await db.auth.signUp({email:d.email.trim(),password:d.password,options:{data:{username:d.username.trim()}}});if(error){showAccountError(error.message);return}if(!data.session){document.getElementById("accountBody").innerHTML=`<div class="notice success">Konto on loodud. Kui Supabase nõuab e-posti kinnitamist, vaata oma Gmaili ja kinnita konto. Seejärel logi sisse.</div>`;return}currentUser=data.user;await loadProfile();closeModal();toast("Konto loodud.");userModal()}}
function showAccountError(m){const x=document.getElementById("accountError");x.textContent=m;x.classList.remove("hidden")}
async function loadProfile(){if(!currentUser){currentProfile=null;return}const {data}=await db.from("profiles").select("id,username,role").eq("id",currentUser.id).maybeSingle();currentProfile=data||null}
function joinModal(){openModal(`<div class="eyebrow">STREAMER</div><h2>Liitu striimerina</h2><p class="muted">Saada oma andmed. Admin vaatab taotluse üle. Konto saad luua eraldi kasutaja vaates.</p><form id="joinForm" class="formgrid"><div class="field"><label>STRIIMERI NIMI</label><input name="name" required maxlength="80"></div><div class="field"><label>GMAIL / E-POST</label><input name="email" type="email" required maxlength="254"></div><div class="field"><label>PLATVORM</label><select name="platform"><option>Twitch</option><option>YouTube</option><option>Kick</option><option>TikTok</option></select></div><div class="field"><label>KANALI URL</label><input name="channel_url" type="url" required></div><div class="field"><label>MIDA SA STRIIMID?</label><input name="game" placeholder="Fortnite"></div><div class="field"><label>AVATARI URL</label><input name="avatar_url" type="url"></div><div class="field"><label>SÕNUM</label><textarea name="message"></textarea></div><div class="modal-actions"><button type="button" class="btn" id="cancelJoin">Tühista</button><button class="primary">SAADA TAOTLUS</button></div><div id="joinError" class="notice error hidden"></div></form>`);document.getElementById("cancelJoin").onclick=closeModal;document.getElementById("joinForm").onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e));const {error}=await db.from("streamer_applications").insert({name:d.name.trim(),email:d.email.trim().toLowerCase(),platform:d.platform,channel_url:d.channel_url.trim(),game:d.game?.trim()||null,avatar_url:d.avatar_url?.trim()||null,message:d.message?.trim()||null,status:"pending"});if(error){const x=document.getElementById("joinError");x.textContent=error.message;x.classList.remove("hidden");return}closeModal();toast("Taotlus saadetud. Admin vaatab selle üle.")}}
async function userModal(){if(!currentUser){accountModal("login");return}await loadProfile();openModal(`<div class="eyebrow">MINU KONTO</div><h2>${esc(currentProfile?.username||currentUser.email?.split("@")[0]||"Kasutaja")}</h2><div id="userPanel"><div class="notice">Laen kontot...</div></div>`);loadUserPanel()}
async function loadUserPanel(){const p=document.getElementById("userPanel");const {data:s,error}=await db.from("streamers").select("*").eq("owner_id",currentUser.id).maybeSingle();if(error){p.innerHTML=`<div class="notice error">${esc(error.message)}</div>`;return}p.innerHTML=`<div class="account-panel"><div class="notice">${esc(currentUser.email||"")} · ${esc(currentProfile?.role||"user")}</div>${s?streamerControls(s):`<div class="notice">Sinu kontoga pole veel kinnitatud striimeriprofiili. Kui admin on sinu taotluse heaks kiitnud, vajuta allolevat nuppu.</div><button class="primary" id="claimBtn">VÕTA OMA STRIIMERIPROFIIL</button>`}<button class="btn" id="logoutUser">LOGI VÄLJA</button></div>`;document.getElementById("logoutUser").onclick=async()=>{await db.auth.signOut();currentUser=null;currentProfile=null;closeModal();toast("Välja logitud.")};document.getElementById("claimBtn")?.addEventListener("click",claimStreamer);document.getElementById("saveUser")?.addEventListener("click",saveUserProfile);document.getElementById("toggleLive")?.addEventListener("click",()=>toggleLive(s));document.getElementById("saveViewers")?.addEventListener("click",()=>saveViewers(s))}
function streamerControls(s){return `<div class="notice">${esc(s.platform)} · ${esc(s.game||"Streaming")} · ${esc(s.channel_url)}</div><div class="live-switch ${s.is_live?"online":""}"><span>STAATUS<br><strong>${s.is_live?"ONLINE":"OFFLINE"}</strong></span><button class="primary" id="toggleLive">${s.is_live?"LÜLITA OFFLINE":"LÜLITA ONLINE"}</button></div><div class="field"><label>VAATAJAD</label><input id="viewerValue" type="number" min="0" value="${Number(s.viewers||0)}"></div><div class="inline-actions"><button class="btn" id="saveViewers">SALVESTA VAATAJAD</button><button class="btn" id="saveUser">VÄRSKENDA</button></div>`}
async function toggleLive(s){const next=!s.is_live;const {error}=await db.from("streamers").update({manual_live:next,is_live:next,manual_viewers:next?Number(s.viewers||0):0,viewers:next?Number(s.viewers||0):0}).eq("id",s.id).eq("owner_id",currentUser.id);if(error){toast(error.message,true);return}toast(next?"Oled nüüd ONLINE.":"Oled nüüd OFFLINE.");await loadStreamers();await loadUserPanel()}
async function saveViewers(s){const v=Math.max(0,Number(document.getElementById("viewerValue").value||0));const {error}=await db.from("streamers").update({manual_live:true,is_live:true,manual_viewers:v,viewers:v}).eq("id",s.id).eq("owner_id",currentUser.id);if(error){toast(error.message,true);return}toast("Vaatajate arv salvestatud.");await loadStreamers();await loadUserPanel()}
async function saveUserProfile(){toast("Profiili värskendamine on valmis järgmises profiiliredaktsioonis.")}
async function claimStreamer(){const {data,error}=await db.rpc("claim_my_streamer");if(error){toast(error.message,true);return}if(!data){toast("Kinnitatud striimeriprofiili ei leitud.",true);return}toast("Striimeriprofiil ühendatud.");await loadStreamers();await loadUserPanel()}
async function adminModal(){if(!currentUser){accountModal("login");return}const {data:{user}}=await db.auth.getUser();if(!user||user.id!==ADMIN_UID){toast("Adminiõigused puuduvad.",true);return}openModal(`<div class="eyebrow">ADMIN PANEL</div><h2>Striimerid & taotlused</h2><div class="account-tabs"><button class="btn primary" id="adminStreamsTab">Striimerid</button><button class="btn" id="adminAppsTab">Taotlused</button></div><div id="adminBody"></div>`);document.getElementById("adminStreamsTab").onclick=()=>loadAdminStreams();document.getElementById("adminAppsTab").onclick=()=>loadAdminApps();loadAdminStreams()}
async function loadAdminStreams(){const b=document.getElementById("adminBody");const {data,error}=await db.from("streamers").select("*").order("name");if(error){b.innerHTML=`<div class="notice error">${esc(error.message)}</div>`;return}b.innerHTML=`<div class="notice">Admini olemasolev striimerite haldus jääb samale tabelile.</div>${data.map(s=>`<div class="app-row"><b>${esc(s.name)}</b><div class="meta">${esc(s.platform)} · ${esc(s.game||"Streaming")} · ${s.is_live?"🔴 LIVE":"offline"}</div><div class="admin-actions"><button class="btn" data-admin-edit="${s.id}">Muuda</button><button class="danger" data-admin-delete="${s.id}">Kustuta</button></div></div>`).join("")||"<div class='empty'>Pole striimereid.</div>"}`;b.querySelectorAll("[data-admin-delete]").forEach(x=>x.onclick=()=>adminDelete(x.dataset.adminDelete));b.querySelectorAll("[data-admin-edit]").forEach(x=>x.onclick=()=>adminEdit(x.dataset.adminEdit))}
async function adminDelete(id){if(!confirm("Kustuta striimer?"))return;const {error}=await db.from("streamers").delete().eq("id",id);if(error){toast(error.message,true);return}toast("Kustutatud.");await loadStreamers();loadAdminStreams()}
function adminEdit(id){const s=streamers.find(x=>x.id===id);if(!s)return;const b=document.getElementById("adminBody");b.innerHTML=`<div class="field"><label>NIMI</label><input id="aName" value="${esc(s.name)}"></div><div class="field"><label>MÄNG</label><input id="aGame" value="${esc(s.game||"")}"></div><div class="field"><label>THUMBNAIL URL</label><input id="aThumb" value="${esc(s.thumbnail_url||"")}"></div><div class="field"><label>KANALI URL</label><input id="aUrl" value="${esc(s.channel_url)}"></div><div class="modal-actions"><button class="btn" id="backAdmin">Tagasi</button><button class="primary" id="saveAdmin">Salvesta</button></div>`;document.getElementById("backAdmin").onclick=loadAdminStreams;document.getElementById("saveAdmin").onclick=async()=>{const {error}=await db.from("streamers").update({name:document.getElementById("aName").value.trim(),game:document.getElementById("aGame").value.trim()||null,thumbnail_url:document.getElementById("aThumb").value.trim()||null,channel_url:document.getElementById("aUrl").value.trim()}).eq("id",id);if(error){toast(error.message,true);return}toast("Salvestatud.");await loadStreamers();loadAdminStreams()}}
async function loadAdminApps(){const b=document.getElementById("adminBody");const {data,error}=await db.from("streamer_applications").select("*").order("created_at",{ascending:false});if(error){b.innerHTML=`<div class="notice error">${esc(error.message)}</div>`;return}b.innerHTML=data.map(a=>`<div class="app-row"><b>${esc(a.name)}</b><div class="meta">${esc(a.email)} · ${esc(a.platform)} · ${esc(a.game||"")}</div><div class="meta">${esc(a.channel_url)}</div><div class="meta">Staatus: <b>${esc(a.status)}</b></div>${a.status==="pending"?`<div class="admin-actions"><button class="primary" data-approve="${a.id}">AKSEPTEERI</button><button class="danger" data-reject="${a.id}">KEELDU</button></div>`:""}</div>`).join("")||"<div class='empty'>Taotlusi pole.</div>";b.querySelectorAll("[data-approve]").forEach(x=>x.onclick=()=>approveApp(x.dataset.approve));b.querySelectorAll("[data-reject]").forEach(x=>x.onclick=()=>rejectApp(x.dataset.reject))}
async function approveApp(id){const {data,error}=await db.rpc("admin_approve_application",{p_application_id:id});if(error){toast(error.message,true);return}toast("Taotlus kinnitatud ja striimeriprofiil loodud.");await loadStreamers();loadAdminApps()}
async function rejectApp(id){const {error}=await db.from("streamer_applications").update({status:"rejected"}).eq("id",id);if(error){toast(error.message,true);return}toast("Taotlus tagasi lükatud.");loadAdminApps()}
document.getElementById("userBtn").onclick=()=>currentUser?userModal():accountModal("login");document.getElementById("adminBtn").onclick=()=>adminModal();document.getElementById("search").oninput=render;document.getElementById("clearGameFilter").onclick=()=>{activeGame=null;render()};platformFilters();db.auth.onAuthStateChange(async(_,session)=>{currentUser=session?.user||null;if(currentUser)await loadProfile()});loadStreamers();
})();