const SUPABASE_URL="https://rrzglnazdppgjjtaswmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_ax0HpMi18hz-AQ2x8XOT3w_gRLYKE4h";
const {createClient}=supabase; const db=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const ADMIN_UID="56a4036e-b37d-4928-abf2-8f49d709f5b7"; let rows=[],filter="Kõik",lastSync=null;
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
const fmt=n=>Number(n||0).toLocaleString("et-EE");
const open=id=>$(id).classList.remove("hidden"), close=id=>$(id).classList.add("hidden");
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>close(b.dataset.close));
$("joinBtn").onclick=()=>open("joinModal");$("aboutJoin").onclick=()=>open("joinModal");$("adminBtn").onclick=()=>open("adminModal");
function twitchLogin(url){try{let u=new URL(url),h=u.hostname.replace(/^www\./,"").toLowerCase();if(h!=="twitch.tv"&&!h.endsWith(".twitch.tv"))return null;return u.pathname.split("/").filter(Boolean)[0]||null}catch{return null}}
function youtubeId(url){try{let u=new URL(url),p=u.pathname.split("/").filter(Boolean);if(p[0]==="channel"&&p[1])return {channel:p[1]};if(p[0]==="@"&&p[1])return {handle:p[1]};if(p[0]?.startsWith("@"))return {handle:p[0].slice(1)};return null}catch{return null}}
function tiktokUser(url){try{let p=new URL(url).pathname.split("/").filter(Boolean);let x=p.find(v=>v.startsWith("@"));return x?x.slice(1):p[0]||null}catch{return null}}
function embed(s){let p=s.platform.toLowerCase();if(p==="twitch"){let l=twitchLogin(s.channel_url);if(!l)return"";return`https://player.twitch.tv/?channel=${encodeURIComponent(l)}&parent=${encodeURIComponent(location.hostname)}&muted=true&autoplay=true`}if(p==="youtube"&&s.live_video_id)return`https://www.youtube.com/embed/${encodeURIComponent(s.live_video_id)}?autoplay=1&mute=1`;if(p==="tiktok"&&tiktokUser(s.channel_url))return`https://www.tiktok.com/embed/live/@${encodeURIComponent(tiktokUser(s.channel_url))}?autoplay=1&muted=1&controls=1&embed_domain=${encodeURIComponent(location.hostname)}`;return""}
function statusBadge(s){if(s.sync_error&&s.last_checked_at===null)return`<span class="badge unknown">⚠ KONTROLL PUUDUB</span>`;return s.is_live?`<span class="badge live">● LIVE</span>`:`<span class="badge offline">OFFLINE</span>`}
function card(s){let e=embed(s),img=s.thumbnail_url||s.avatar_url||"";return`<article class="card"><div class="media" style="background-image:url('${esc(img)}')">${statusBadge(s)}<span class="watchers">👁 ${fmt(s.viewers)}${s.is_live?" vaatajat":""}</span><span class="plat">${esc(s.platform)}</span>${e&&s.is_live?`<div class="preview"><iframe src="${e}" allow="autoplay;fullscreen" loading="lazy"></iframe></div>`:""}</div><div class="card-body"><div class="person"><img class="avatar" src="${esc(s.avatar_url||img)}" onerror="this.style.visibility='hidden'"><div><h3>${esc(s.name)}</h3><div class="game">${esc(s.game||"Mäng määramata")}</div></div></div><div class="card-meta"><span class="status-text">${s.is_live?"LIVE praegu":"OFFLINE"}${s.last_checked_at?" · kontrollitud "+new Date(s.last_checked_at).toLocaleTimeString("et-EE",{hour:"2-digit",minute:"2-digit"}):""}</span><a class="watch-link" target="_blank" rel="noopener" href="${esc(s.channel_url)}">${s.is_live?"VAATA LIVE →":"AVA KANAL →"}</a></div></div></article>`}
function render(){let filtered=rows.filter(s=>filter==="Kõik"||s.platform===filter),live=filtered.filter(s=>s.is_live),q=$("search").value.trim().toLowerCase();let searched=filtered.filter(s=>!q||s.name.toLowerCase().includes(q)||String(s.game||"").toLowerCase().includes(q));$("liveGrid").innerHTML=live.map(card).join("");$("allGrid").innerHTML=searched.map(card).join("");$("liveEmpty").classList.toggle("hidden",live.length>0);$("liveCount").textContent=fmt(rows.filter(s=>s.is_live).length);$("viewerCount").textContent=fmt(rows.filter(s=>s.is_live).reduce((a,s)=>a+Number(s.viewers||0),0));$("streamerCount").textContent=fmt(rows.length);if(lastSync){$("heroStatus").textContent=rows.length?`${live.length} LIVE`: "KÕIK OFFLINE";$("heroChecked").textContent=`Viimane andmete laadimine ${lastSync.toLocaleTimeString("et-EE",{hour:"2-digit",minute:"2-digit"})}`;$("footerSync").textContent=`Automaatne kontroll · ${lastSync.toLocaleTimeString("et-EE",{hour:"2-digit",minute:"2-digit"})}`}}
async function load(){let {data,error}=await db.from("streamers").select("*").order("is_live",{ascending:false}).order("viewers",{ascending:false});if(error){console.error(error);return}rows=data||[];lastSync=new Date();render()}
$("search").oninput=render;
["Kõik","Twitch","YouTube","Kick","TikTok"].forEach(p=>{let b=document.createElement("button");b.className="filter"+(p==="Kõik"?" active":"");b.textContent=p;b.onclick=()=>{filter=p;document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");render()};$("filters").appendChild(b)});
$("joinForm").onsubmit=async e=>{e.preventDefault();let st=$("joinStatus");st.textContent="Saadan...";if($("honeypot").value)return;let payload={name:$("joinName").value.trim(),platform:$("joinPlatform").value,channel_url:$("joinUrl").value.trim(),email:$("joinEmail").value.trim(),message:$("joinMessage").value.trim()};let {error}=await db.from("streamer_applications").insert(payload);if(error){st.className="error";st.textContent=error.message}else{st.className="ok";st.textContent="Avaldus saadetud!";e.target.reset()}};
$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginError").textContent="";let {data,error}=await db.auth.signInWithPassword({email:$("loginEmail").value,password:$("loginPassword").value});if(error){$("loginError").className="error";$("loginError").textContent=error.message;return}if(data.user?.id!==ADMIN_UID){await db.auth.signOut();$("loginError").className="error";$("loginError").textContent="Sul puuduvad adminiõigused.";return}showAdmin()};
async function showAdmin(){$("loginView").classList.add("hidden");$("adminView").classList.remove("hidden");await renderAdmin();await renderApps()}
$("logoutBtn").onclick=async()=>{await db.auth.signOut();$("adminView").classList.add("hidden");$("loginView").classList.remove("hidden")};
async function renderAdmin(){let {data,error}=await db.from("streamers").select("*").order("created_at",{ascending:false});if(error){$("adminError").className="error";$("adminError").textContent=error.message;return}$("adminList").innerHTML=(data||[]).map(s=>`<div class="admin-row"><div><strong>${esc(s.name)} ${s.is_live?"🔴 LIVE":"⚫ OFFLINE"}</strong><small>${esc(s.platform)} · ${fmt(s.viewers)} viewers · ${esc(s.game||"mäng määramata")} · ${s.last_checked_at?"kontrollitud":"pole kontrollitud"}</small></div><div class="admin-buttons"><button onclick='editStreamer(${JSON.stringify(s).replace(/'/g,"&#39;")})'>MUUDA</button><button class="danger" onclick="deleteStreamer('${s.id}')">KUSTUTA</button></div></div>`).join("")}
window.editStreamer=s=>{$("editId").value=s.id;$("name").value=s.name;$("platform").value=s.platform;$("url").value=s.channel_url;$("game").value=s.game||"";$("avatar").value=s.avatar_url||"";$("saveBtn").textContent="SALVESTA";$("cancelEdit").classList.remove("hidden")};
$("cancelEdit").onclick=()=>{ $("streamerForm").reset();$("editId").value="";$("saveBtn").textContent="LISA STRIIMER";$("cancelEdit").classList.add("hidden")};
$("streamerForm").onsubmit=async e=>{e.preventDefault();let p={p_avatar_url:$("avatar").value.trim()||null,p_channel_url:$("url").value.trim(),p_game:$("game").value.trim()||null,p_name:$("name").value.trim(),p_platform:$("platform").value};let r=$("editId").value?await db.from("streamers").update({name:p.p_name,platform:p.p_platform,channel_url:p.p_channel_url,game:p.p_game,avatar_url:p.p_avatar_url}).eq("id",$("editId").value):await db.rpc("admin_add_streamer",p);if(r.error){$("adminError").className="error";$("adminError").textContent=r.error.message;return}$("adminError").className="ok";$("adminError").textContent="Salvestatud. Live kontroll toimub taustal."; $("streamerForm").reset();$("editId").value="";$("saveBtn").textContent="LISA STRIIMER";$("cancelEdit").classList.add("hidden");await renderAdmin();await load()};
window.deleteStreamer=async id=>{if(!confirm("Kustuta striimer?"))return;let {error}=await db.from("streamers").delete().eq("id",id);if(error){$("adminError").className="error";$("adminError").textContent=error.message;return}await renderAdmin();await load()};
async function renderApps(){let {data}=await db.from("streamer_applications").select("*").order("created_at",{ascending:false});$("applicationsList").innerHTML=(data||[]).map(a=>`<div class="app"><b>${esc(a.name)}</b> · ${esc(a.platform)} · ${esc(a.status)}<br><span>${esc(a.channel_url)} · ${esc(a.email)}</span>${a.message?`<p>${esc(a.message)}</p>`:""}<div class="app-actions"><button onclick="appStatus('${a.id}','approved')">KINNITA</button><button onclick="appStatus('${a.id}','rejected')">KEELDU</button></div></div>`).join("")}
window.appStatus=async(id,status)=>{let {error}=await db.from("streamer_applications").update({status}).eq("id",id);if(error)alert(error.message);else renderApps()};
db.auth.getSession().then(({data})=>{if(data.session?.user?.id===ADMIN_UID)showAdmin()});load();setInterval(load,30000);
