const SUPABASE_URL="https://rrzglnazdppgjjtaswmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_ax0HpMi18hz-AQ2x8XOT3w_gRLYKE4h";
const ADMIN_UID="56a4036e-b37d-4928-abf2-8f49d709f5b7";
const {createClient}=supabase;const db=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
let streamers=[],activePlatform="all";const fallbackThumb="https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=900&q=80";
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function card(s){const a=s.avatar_url||`https://api.dicebear.com/9.x/adventurer/svg?seed=${encodeURIComponent(s.name)}`,t=s.thumbnail_url||fallbackThumb;return `<article class="card"><div class="thumb" style="background-image:url('${esc(t)}')">${s.is_live?`<span class="live-badge">● LIVE</span><span class="viewers">👁 ${Number(s.viewers||0).toLocaleString("et-EE")}</span>`:`<span class="platform">OFFLINE</span>`}<span class="platform">${esc(s.platform)}</span></div><div class="card-body"><div class="person"><img class="avatar" src="${esc(a)}" alt=""><div><h3>${esc(s.name)}</h3><div class="game">${esc(s.game||"Streaming")}</div></div></div><a class="watch" href="${esc(s.channel_url)}" target="_blank" rel="noopener">${s.is_live?"VAATA LIVE'I  →":"AVA KANAL  →"}</a></div></article>`}
async function loadStreamers(){const {data,error}=await db.from("streamers").select("*").order("is_live",{ascending:false}).order("viewers",{ascending:false});if(error){console.error(error);showError("Andmebaasiga ühendamisel tekkis viga: "+error.message);return}streamers=data||[];render()}
function render(){const live=streamers.filter(s=>s.is_live);document.getElementById("liveCount").textContent=live.length;document.getElementById("viewerCount").textContent=live.reduce((a,s)=>a+Number(s.viewers||0),0).toLocaleString("et-EE");document.getElementById("streamerCount").textContent=streamers.length;renderLive();renderAll();renderAdminList()}
function renderLive(){const q=document.getElementById("search").value.toLowerCase(),d=streamers.filter(s=>s.is_live&&(activePlatform==="all"||s.platform===activePlatform)&&s.name.toLowerCase().includes(q));document.getElementById("liveGrid").innerHTML=d.map(card).join("");document.getElementById("emptyLive").classList.toggle("hidden",d.length>0)}
function renderAll(){const q=document.getElementById("search").value.toLowerCase();document.getElementById("allGrid").innerHTML=streamers.filter(s=>s.name.toLowerCase().includes(q)).map(card).join("")}
function openAdmin(){document.getElementById("adminModal").classList.remove("hidden");checkSession()}function closeAdmin(){document.getElementById("adminModal").classList.add("hidden")}
async function checkSession(){const {data}=await db.auth.getSession(),u=data.session?.user,isAdmin=u?.id===ADMIN_UID;document.getElementById("loginView").classList.toggle("hidden",!!isAdmin);document.getElementById("adminView").classList.toggle("hidden",!isAdmin);if(isAdmin)renderAdminList()}
async function login(e){e.preventDefault();const email=document.getElementById("loginEmail").value.trim(),password=document.getElementById("loginPassword").value,box=document.getElementById("loginError");box.classList.add("hidden");const {data,error}=await db.auth.signInWithPassword({email,password});if(error){box.textContent=error.message;box.classList.remove("hidden");return}if(data.user.id!==ADMIN_UID){await db.auth.signOut();box.textContent="Sellel kontol ei ole StreamHubi adminiõigusi.";box.classList.remove("hidden");return}checkSession()}
async function logout(){await db.auth.signOut();checkSession()}
async function saveStreamer(e){e.preventDefault();const box=document.getElementById("adminError");box.classList.add("hidden");const {data:{user}}=await db.auth.getUser();if(!user||user.id!==ADMIN_UID){box.textContent="Admini sessioon puudub.";box.classList.remove("hidden");return}const id=document.getElementById("editId").value,p={name:document.getElementById("name").value.trim(),platform:document.getElementById("platform").value,channel_url:document.getElementById("url").value.trim(),game:document.getElementById("game").value.trim()||null,avatar_url:document.getElementById("avatar").value.trim()||null,thumbnail_url:document.getElementById("thumbnail").value.trim()||null,is_live:document.getElementById("live").checked,viewers:Math.max(0,Number(document.getElementById("viewers").value||0)),updated_at:new Date().toISOString()};let r=id?await db.from("streamers").update(p).eq("id",id).select().single():await db.from("streamers").insert(p).select().single();if(r.error){box.textContent=r.error.message;box.classList.remove("hidden");return}cancelEdit();await loadStreamers()}
function editStreamer(id){const s=streamers.find(x=>x.id===id);if(!s)return;document.getElementById("editId").value=s.id;document.getElementById("name").value=s.name||"";document.getElementById("platform").value=s.platform||"Twitch";document.getElementById("url").value=s.channel_url||"";document.getElementById("game").value=s.game||"";document.getElementById("avatar").value=s.avatar_url||"";document.getElementById("thumbnail").value=s.thumbnail_url||"";document.getElementById("live").checked=!!s.is_live;document.getElementById("viewers").value=Number(s.viewers||0);document.getElementById("saveBtn").textContent="Salvesta muudatus";document.getElementById("cancelEdit").classList.remove("hidden");document.getElementById("name").focus()}
function cancelEdit(){document.getElementById("streamerForm").reset();document.getElementById("editId").value="";document.getElementById("viewers").value=0;document.getElementById("saveBtn").textContent="Lisa striimer";document.getElementById("cancelEdit").classList.add("hidden")}
async function deleteStreamer(id){const s=streamers.find(x=>x.id===id);if(!s||!confirm(`Kustuta ${s.name}?`))return;const {error}=await db.from("streamers").delete().eq("id",id);if(error){const b=document.getElementById("adminError");b.textContent=error.message;b.classList.remove("hidden");return}await loadStreamers()}
function renderAdminList(){const el=document.getElementById("adminList");if(!el)return;if(!streamers.length){el.innerHTML='<div class="empty">Andmebaasis pole veel ühtegi striimerit.</div>';return}el.innerHTML=streamers.map(s=>`<div class="admin-row"><div><strong>${esc(s.name)}</strong><span>${esc(s.platform)} · ${esc(s.game||"Streaming")} · ${s.is_live?"🔴 LIVE":"offline"}</span></div><div class="admin-row-actions"><button class="secondary small-btn" onclick="editStreamer('${s.id}')">Muuda</button><button class="danger-btn" onclick="deleteStreamer('${s.id}')">Kustuta</button></div></div>`).join("")}
function showError(m){document.getElementById("liveGrid").innerHTML=`<div class="empty" style="grid-column:1/-1">${esc(m)}</div>`}
document.querySelectorAll(".filter").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");activePlatform=b.dataset.filter;renderLive()}));
document.getElementById("search").addEventListener("input",()=>{renderLive();renderAll()});document.getElementById("loginForm").addEventListener("submit",login);document.getElementById("streamerForm").addEventListener("submit",saveStreamer);db.auth.onAuthStateChange(()=>checkSession());loadStreamers();
