// STREAMHUB V40 CONFIG
// ÄRA JAGA SUPABASE SERVICE_ROLE KEY-i.
// Kasuta ainult anon/publishable key'd.
window.STREAMHUB_CONFIG = {
  SUPABASE_URL: "SINU_SUPABASE_PROJECT_URL",
  SUPABASE_PUBLISHABLE_KEY: "SINU_SUPABASE_PUBLISHABLE_KEY"
};